<a href="https://colab.research.google.com/github/roshain-wijewardene/Random-forest-classifier/blob/main/S14245_Random_Forest_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment : Random Forest**
*   **Name : D. R. R. Wijewardene**
*   **Index no. : S14245**
*   **Faculty : Science**

# **Dataset : Symptoms and Diagnosis for Inflammation of urinary bladder**

This dataset was created by a medical expert to perform the presumptive diagnosis of a
disease of the urinary system, "Inflammation of urinary bladder".

**Symptoms :**

*   Temperature of patient
*   Occurrence of nausea
*   Lumbar pain
*   Urine pushing (continuous need for urination)
*   Micturition pains
*   Burning of urethra, itch, swelling of urethra outlet

**Diagnosis for Inflammation of urinary bladder :**

*   yes
*   no

# Import Libraries

In [ ]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier     #Scikit's random forest classifier library

# Import Dataset
*Originally obtained from the UCI Machine Learning Repository but a .csv version is uploaded through the GitHub.*

In [ ]:
dataset= pd.read_csv('https://raw.githubusercontent.com/RoshainW/Diagnosis/main/diagnosis.csv')
dataset.head(10)

Body Temperature  ... Inflammation of Urinary Bladder
0                37  ...                             yes
1                39  ...                              no
2                37  ...                              no
3                41  ...                              no
4                36  ...                             yes
5                38  ...                              no
6                41  ...                              no
7                41  ...                              no
8                37  ...                              no
9                36  ...                             yes

[10 rows x 7 columns]

# Rearrange the dataset

**Replace "yes" with 1 and "no" with 0**

In [ ]:
dataset['Nausea'] = dataset['Nausea'].map({"no":0,"yes":1})
dataset['Lumbar Pain'] = dataset['Lumbar Pain'].map({"no":0,"yes":1})
dataset['Urine Pushing'] = dataset['Urine Pushing'].map({"no":0,"yes":1})
dataset['Micturition Pains'] = dataset['Micturition Pains'].map({"no":0,"yes":1})
dataset['Urethra outlet burn/itch/swell'] = dataset['Urethra outlet burn/itch/swell'].map({"no":0,"yes":1})
dataset['Inflammation of Urinary Bladder'] = dataset['Inflammation of Urinary Bladder'].map({"no":0,"yes":1})

dataset.head(10)

Body Temperature  ...  Inflammation of Urinary Bladder
0                37  ...                                1
1                39  ...                                0
2                37  ...                                0
3                41  ...                                0
4                36  ...                                1
5                38  ...                                0
6                41  ...                                0
7                41  ...                                0
8                37  ...                                0
9                36  ...                                1

[10 rows x 7 columns]

**Assign a random number between 0 and 1 to each row**

In [ ]:
np.random.seed(0)     #to initialize the random number generator and customize the start number

#to separate approximately 80% as training data and the rest as testing data;
        #if random value is <=0.8 true, else false
dataset['train or not'] = np.random.uniform(0,1, len(dataset)) <= 0.8

dataset.head(10)

Body Temperature  Nausea  ...  Inflammation of Urinary Bladder  train or not
0                37       0  ...                                1          True
1                39       0  ...                                0          True
2                37       0  ...                                0          True
3                41       0  ...                                0          True
4                36       0  ...                                1          True
5                38       0  ...                                0          True
6                41       0  ...                                0          True
7                41       0  ...                                0         False
8                37       0  ...                                0         False
9                36       0  ...                                1          True

[10 rows x 8 columns]

**Creating training set and testing set from initial dataset**

In [ ]:
train_set = dataset[dataset['train or not']==True]
test_set = dataset[dataset['train or not']==False]

In [ ]:
print('Number of diagnostic data in the training set : ', len(train_set))
print('Number of diagnostic data in the testing set : ', len(test_set))

Number of diagnostic data in the training set :  99
Number of diagnostic data in the testing set :  21


# Training Set

In [ ]:
train_set.head(10)

Body Temperature  Nausea  ...  Inflammation of Urinary Bladder  train or not
0                 37       0  ...                                1          True
1                 39       0  ...                                0          True
2                 37       0  ...                                0          True
3                 41       0  ...                                0          True
4                 36       0  ...                                1          True
5                 38       0  ...                                0          True
6                 41       0  ...                                0          True
9                 36       0  ...                                1          True
10                37       0  ...                                1          True
11                38       0  ...                                0          True

[10 rows x 8 columns]

# Testing Set

In [ ]:
test_set.head(10)

Body Temperature  Nausea  ...  Inflammation of Urinary Bladder  train or not
7                 41       0  ...                                0         False
8                 37       0  ...                                0         False
13                37       0  ...                                1         False
17                37       0  ...                                1         False
19                40       1  ...                                0         False
20                35       0  ...                                1         False
27                37       0  ...                                1         False
38                41       0  ...                                0         False
52                37       0  ...                                1         False
66                40       1  ...                                0         False

[10 rows x 8 columns]

# The Symptoms

In [ ]:
symptoms = dataset.columns[:6]
symptoms

Index(['Body Temperature', 'Nausea', 'Lumbar Pain', 'Urine Pushing',
       'Micturition Pains', 'Urethra outlet burn/itch/swell'],
      dtype='object')

# The Diagnosis for each instance in Training set

In [ ]:
diagnosis = np.array(train_set['Inflammation of Urinary Bladder'])
diagnosis

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1])

# Random Forest Classifier

**Defining**



In [ ]:
rfc = RandomForestClassifier()    #Random Forest Classifier - rfc

**Training**
> Train to symptoms and diagnosis of Training set

In [ ]:
rfc.fit(train_set[symptoms],diagnosis)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

**Applying to Testing set**

In [ ]:
rfc.predict(test_set[symptoms])

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0])


> Probability of the prediction being "no" or "yes"

In [ ]:
#predicted probablities
rfc.predict_proba(test_set[symptoms])

array([[1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.99, 0.01],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.99, 0.01],
       [0.03, 0.97],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.18, 0.82],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.18, 0.82],
       [1.  , 0.  ],
       [1.  , 0.  ]])

# Comparison between Predicted Diagnosis and Actual Diagnosis

> **Predicted Diagnostic Result**

In [ ]:
#possible diagnosis results
pos_results = np.array(['no','yes'])

#predicted diagnosis for testing set
predicted_diagnosis = pos_results[rfc.predict(test_set[symptoms])]
predicted_diagnosis

array(['no', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no',
       'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'no', 'yes', 'no',
       'no'], dtype='<U3')

> **Actual Diagnostic Result**

In [ ]:
actual_diagnosis = test_set['Inflammation of Urinary Bladder'].map({0:"no",1:"yes"})
actual_diagnosis

7       no
8       no
13     yes
17     yes
19      no
20     yes
27     yes
38      no
52     yes
66      no
68     yes
70     yes
72      no
89     yes
98     yes
103    yes
109     no
111     no
114    yes
116     no
118     no
Name: Inflammation of Urinary Bladder, dtype: object



> **Comparison**



In [ ]:
#create matrix to compare
comparison = pd.crosstab(actual_diagnosis,predicted_diagnosis,rownames=["Actual Diagnosis"], colnames=["Predicted Diagnosis"])
comparison

Predicted Diagnosis  no  yes
Actual Diagnosis            
no                   10    0
yes                   0   11

# Applying to a new instance

In [ ]:
predicted_diagnosis = pos_results[rfc.predict([[37,1,0,1,0,1]])]
print("\"Inflammation of Urinary Bladder\"\nDiagnosis result : ",predicted_diagnosis[0])

"Inflammation of Urinary Bladder"
Diagnosis result :  yes
